/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PredictSetupRouteImport } from './routes/predict-setup'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OauthFinishRouteImport } from './routes/oauth-finish'
import { Route as MemwalSetupRouteImport } from './routes/memwal-setup'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as UNameRouteImport } from './routes/u.$name'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'
import { Route as MemwalRevokeRouteImport } from './routes/memwal.revoke'
import { Route as FollowAddressRouteImport } from './routes/follow.$address'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as UNameWeekRouteImport } from './routes/u.$name.$week'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictSetupRoute = PredictSetupRouteImport.update({
  id: '/predict-setup',
  path: '/predict-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthFinishRoute = OauthFinishRouteImport.update({
  id: '/oauth-finish',
  path: '/oauth-finish',
  getParentRoute: () => rootRouteImport,
} as any)
const MemwalSetupRoute = MemwalSetupRouteImport.update({
  id: '/memwal-setup',
  path: '/memwal-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const UNameRoute = UNameRouteImport.update({
  id: '/u/$name',
  path: '/u/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemwalRevokeRoute = MemwalRevokeRouteImport.update({
  id: '/memwal/revoke',
  path: '/memwal/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowAddressRoute = FollowAddressRouteImport.update({
  id: '/follow/$address',
  path: '/follow/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UNameWeekRoute = UNameWeekRouteImport.update({
  id: '/$week',
  path: '/$week',
  getParentRoute: () => UNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/leaderboard': typeof LeaderboardRoute
  '/memwal-setup': typeof MemwalSetupRoute
  '/oauth-finish': typeof OauthFinishRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/predict': typeof PredictRoute
  '/predict-setup': typeof PredictSetupRoute
  '/privacy': typeof PrivacyRoute
  '/protocol': typeof ProtocolRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/follow/$address': typeof FollowAddressRoute
  '/memwal/revoke': typeof MemwalRevokeRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/u/$name': typeof UNameRouteWithChildren
  '/docs': typeof DocsIndexRoute
  '/u/$name/$week': typeof UNameWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/leaderboard': typeof LeaderboardRoute
  '/memwal-setup': typeof MemwalSetupRoute
  '/oauth-finish': typeof OauthFinishRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/predict': typeof PredictRoute
  '/predict-setup': typeof PredictSetupRoute
  '/privacy': typeof PrivacyRoute
  '/protocol': typeof ProtocolRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/follow/$address': typeof FollowAddressRoute
  '/memwal/revoke': typeof MemwalRevokeRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/u/$name': typeof UNameRouteWithChildren
  '/docs': typeof DocsIndexRoute
  '/u/$name/$week': typeof UNameWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/leaderboard': typeof LeaderboardRoute
  '/memwal-setup': typeof MemwalSetupRoute
  '/oauth-finish': typeof OauthFinishRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/predict': typeof PredictRoute
  '/predict-setup': typeof PredictSetupRoute
  '/privacy': typeof PrivacyRoute
  '/protocol': typeof ProtocolRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/follow/$address': typeof FollowAddressRoute
  '/memwal/revoke': typeof MemwalRevokeRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/u/$name': typeof UNameRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/u/$name/$week': typeof UNameWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/audit'
    | '/auth'
    | '/coach'
    | '/leaderboard'
    | '/memwal-setup'
    | '/oauth-finish'
    | '/onboarding'
    | '/portfolio'
    | '/predict'
    | '/predict-setup'
    | '/privacy'
    | '/protocol'
    | '/setup'
    | '/terms'
    | '/trade'
    | '/docs/$slug'
    | '/follow/$address'
    | '/memwal/revoke'
    | '/receipt/$id'
    | '/u/$name'
    | '/docs'
    | '/u/$name/$week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/audit'
    | '/auth'
    | '/coach'
    | '/leaderboard'
    | '/memwal-setup'
    | '/oauth-finish'
    | '/onboarding'
    | '/portfolio'
    | '/predict'
    | '/predict-setup'
    | '/privacy'
    | '/protocol'
    | '/setup'
    | '/terms'
    | '/trade'
    | '/docs/$slug'
    | '/follow/$address'
    | '/memwal/revoke'
    | '/receipt/$id'
    | '/u/$name'
    | '/docs'
    | '/u/$name/$week'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/audit'
    | '/auth'
    | '/coach'
    | '/leaderboard'
    | '/memwal-setup'
    | '/oauth-finish'
    | '/onboarding'
    | '/portfolio'
    | '/predict'
    | '/predict-setup'
    | '/privacy'
    | '/protocol'
    | '/setup'
    | '/terms'
    | '/trade'
    | '/docs/$slug'
    | '/follow/$address'
    | '/memwal/revoke'
    | '/receipt/$id'
    | '/u/$name'
    | '/docs/'
    | '/u/$name/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MemwalSetupRoute: typeof MemwalSetupRoute
  OauthFinishRoute: typeof OauthFinishRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  PredictRoute: typeof PredictRoute
  PredictSetupRoute: typeof PredictSetupRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtocolRoute: typeof ProtocolRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  TradeRoute: typeof TradeRoute
  DocsSlugRoute: typeof DocsSlugRoute
  FollowAddressRoute: typeof FollowAddressRoute
  MemwalRevokeRoute: typeof MemwalRevokeRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  UNameRoute: typeof UNameRouteWithChildren
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict-setup': {
      id: '/predict-setup'
      path: '/predict-setup'
      fullPath: '/predict-setup'
      preLoaderRoute: typeof PredictSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-finish': {
      id: '/oauth-finish'
      path: '/oauth-finish'
      fullPath: '/oauth-finish'
      preLoaderRoute: typeof OauthFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memwal-setup': {
      id: '/memwal-setup'
      path: '/memwal-setup'
      fullPath: '/memwal-setup'
      preLoaderRoute: typeof MemwalSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$name': {
      id: '/u/$name'
      path: '/u/$name'
      fullPath: '/u/$name'
      preLoaderRoute: typeof UNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memwal/revoke': {
      id: '/memwal/revoke'
      path: '/memwal/revoke'
      fullPath: '/memwal/revoke'
      preLoaderRoute: typeof MemwalRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow/$address': {
      id: '/follow/$address'
      path: '/follow/$address'
      fullPath: '/follow/$address'
      preLoaderRoute: typeof FollowAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$name/$week': {
      id: '/u/$name/$week'
      path: '/$week'
      fullPath: '/u/$name/$week'
      preLoaderRoute: typeof UNameWeekRouteImport
      parentRoute: typeof UNameRoute
    }
  }
}

interface UNameRouteChildren {
  UNameWeekRoute: typeof UNameWeekRoute
}

const UNameRouteChildren: UNameRouteChildren = {
  UNameWeekRoute: UNameWeekRoute,
}

const UNameRouteWithChildren = UNameRoute._addFileChildren(UNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  LeaderboardRoute: LeaderboardRoute,
  MemwalSetupRoute: MemwalSetupRoute,
  OauthFinishRoute: OauthFinishRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  PredictRoute: PredictRoute,
  PredictSetupRoute: PredictSetupRoute,
  PrivacyRoute: PrivacyRoute,
  ProtocolRoute: ProtocolRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  TradeRoute: TradeRoute,
  DocsSlugRoute: DocsSlugRoute,
  FollowAddressRoute: FollowAddressRoute,
  MemwalRevokeRoute: MemwalRevokeRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  UNameRoute: UNameRouteWithChildren,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
